default: &default
  adapter: datomic
  uri: <%= ENV.fetch("DATOMIC_URI", "datomic:dev://localhost:4334/animal-tracker") %>
  transport: peer

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
