AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 250

Metrics:
  Enabled: false

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false
