protocol=dev
host=datomic
port=4334
alt-host=datomic
h2-port=4335
data-dir=/var/lib/datomic
memory-index-threshold=32m
memory-index-max=256m
object-cache-max=128m
storage-access=remote
storage-admin-password=chronicle-admin
storage-datomic-password=chronicle-datomic
