source "https://rubygems.org"
ruby ">= 3.4.0"

gem "active-chronicle", path: "../.."
gem "rails", "~> 8.1.4"
gem "puma", ">= 5.0"
gem "propshaft"
gem "jbuilder"
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
end
