source "https://rubygems.org"
ruby ">= 3.4.0"

gem "active-chronicle", path: "../.."
gem "rails", "~> 8.1.4"
gem "propshaft"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "tzinfo-data", platforms: %i[windows jruby]
